### ISSUE TITLE
Support for integrated versions of placables

### ISSUE THREAD

**Issue by Dzi4d3k** [DeckerMMIV/FarmSim_Mod_Glance#7]
Hi,

I've checked glance version 2.4.1 with Norgeholm v2.4, where lumber-mill is integrated into map, and glance doesn't show anything about it.
This map has also integrated greenhouse with salad.

Regards.

**Comment by DeckerMMIV** [comment]
Sorry, but that is going to be a never ending adaption of the Glance script, attempting to support whatever objects have been embedded/integrated into map-mods.

I would suggest that you suggest to the map-maker of Norgeholm, that he uses the placeable mods and sets the `defaultVehicles.xml` to reflect that. - I recon that he already supplies a 'mod pack' with his map, as I've previously seen he modified my SoilManagement.ZIP.
And since he's probably using uploaded.to for his map, I won't spend my time with that.

**Comment by Dzi4d3k** [comment]
I not intended to encourage you to follow any map maker. Norgeholm was just example cause we play on it. I assumed that integrated placeable mods could be recognized like standalone are. If I'm wrong then take my apologies.
Upoladed.to would not be a problem, cause I can re-upload map to faster place like google drive, but I'll also contact map maker.

Edit:
Now I wonder, do lumber mill, and lettuce resources and products can be displayed like pigs and cattle forage and others are.
